stages:
  - build
  - test

variables:
  GO_VERSION: "1.23.1"
  COVERAGE_THRESHOLD: "30.0" # Порог покрытия кода для тестов

before_script:
  - git config --global url."https://$GIT_USER:$GIT_TOKEN@gitlab.crja72.ru/".insteadOf "https://gitlab.crja72.ru/"
  - go mod tidy
  - go version

build:
  stage: build
  image: golang:${GO_VERSION}
  variables:
    GIT_STRATEGY: clone
  script:
    - ls -la    # Отладка: покажет структуру
    - go build -o bin/sso ./cmd/sso/main.go