stages:
  - build
  - test

variables:
  GO_VERSION: "1.23.1"
  COVERAGE_THRESHOLD: "30.0" # Порог покрытия кода для тестов

before_script:
  - go version
  - go mod tidy

build:
  stage: build
  image: golang:${GO_VERSION}
  script:
    - go build -o /app/bin/sso ./cmd/sso/main.go
  artifacts:
    paths:
      - go.sum
      - go.mod