stages:
  - build
  - test

variables:
  GO_VERSION: "1.23.1"
  COVERAGE_THRESHOLD: "30.0" # Порог покрытия кода для тестов

before_script:
  - go version

build:
  stage: build
  image: golang:${GO_VERSION}
  variables:
    GIT_STRATEGY: clone
  script:
    - ls -la    # Отладка: покажет структуру
    - go build -mod=vendor -o bin/sso ./cmd/sso/main.go