stages:
  - build
  - test

variables:
  GO_VERSION: "1.23.1"
  COVERAGE_THRESHOLD: "30.0"

default:
  image: golang:${GO_VERSION}
  variables:
    GIT_STRATEGY: clone
  before_script:
    - go version

build:
  stage: build
  script:
    - mkdir -p bin
    - go mod vendor
    - go build -mod=vendor -o bin/sso ./cmd/sso/main.go
  artifacts:
    paths:
      - bin/sso