env: "local" # prod

jwt:
  app_secret_a:  # секретный ключ для шифрования access токенов
  app_secret_b:  # секретный ключ для шифрования refresh токенов
  access_token_ttl: 15m # время жизни access токена
  refresh_token_ttl: 720h # время жизни refresh токена

grpc:
  port: 50051
  timeout: 5s # время обработки запроса 

POSTGRES:
  POSTGRES_HOST: localhost
  POSTGRES_PORT: 5432
  POSTGRES_USER: admin
  POSTGRES_PASS: admin
  POSTGRES_DB: test_db
  POSTGRES_SSLMODE: disable

  POSTGRES_MAX_CONN: 10
  POSTGRES_MIN_CONN: 5